name: "LogisticRegression"
# dataset_path: "./data/wine.data"
dataset_path: "./HA-03&04_Classification_and_Logistic_Regression/data/wine.data" #debug
wandb_on_off: false         
lr: 1e-3
epoch: 9000
tol: 0
gd: "SGD"   # available: "SGD" "MBGD"

wandb:
  project: "Logistic Regression"
  # dir: "./outputs"