name: "LogisticRegression"
# dataset_path: "./data/wine.data"
dataset_path: "/home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/data/wine.data" #debug
wandb_on_off: false        
lr: 1e-45
epoch: 1000
tol: 1e-6
gd: "SGD"   # available: "SGD" "MBGD"

wandb:
  project: "Logistic Regression"
  # dir: "./outputs"