name: "Perceptron"
# dataset_path: "./data/wine.data"
dataset_path: "/home/hgj/SDM274/HA-03&04_Classification_and_Logistic_Regression/data/wine.data" #debug
wandb_on_off: true          
lr: 0.01
epoch: 9000
tol: 0.00001
gd: "SGD"   # available: "SGD" "BGD"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  project: "Perceptron"
  # dir: "./outputs"