name: "Perceptron"
dataset_path: "./data/wine.data"
wandb_on_off: true          
lr: 0.01
epoch: 9000
tol: 0.00001
gd: "SGD"   # available: "SGD" "BGD"

wandb:
  project: "Perceptron"
  # dir: "./outputs"