name: "Project_midterm"
dataset: './Project_midterm/data/ai4i2020.csv'
wandb_on_off: false 
lr_linear_regression: 1e-6       
lr: 1e-2
epoch: 4000
batch_size: 800
tol: 1e-6
gd: "MBGD"   # available: "SGD" "MBGD"
hidden_layers : [10]
k : 5 # k-fold


defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  project: "MLP"
  # dir: "./outputs"