name: "MLP"
wandb_on_off: false        
lr: 1e-2
epoch: 8000
tol: 1e-6
gd: "SGD"   # available: "SGD" "MBGD"
input_size : 1 # Nonlinear, 2 when Classifier
batch_size: 10
layers_list : [[input_size, 10, 1], [input_size, 20, 1], [input_size, 10, 20, 1]]
k : 5 # k-fold
mission : "Classifier" # available: "Nonlinear" "Classifier"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  project: "MLP"
  # dir: "./outputs"