name: "MLP"
# dataset_path: "/home/hgj/SDM274/HA-05_Multilayer_Perceptron/data/color_dataset.csv" #ubuntu
dataset_path: "./data/color_dataset.csv" #windows
wandb_on_off: false        
lr: 1e-4
epoch: 10000
tol: 1e-6
gd: "SGD"   # available: "SGD" "MBGD"
input_size: 3 
batch_size: 10
num_classes: 3
loss_function: "cross_entropy"
activation_function: "sigmoid" # available: "sigmoid" "ReLU" "tanh"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  project: "MLP"
  # dir: "./outputs"