name: "MLP"
# dataset_path: "./data/wine.data"
dataset_path: "/home/hgj/SDM274/HA-05_Multilayer_Perceptron/data/color_dataset.csv" #debug
wandb_on_off: false        
lr: 1e-45
epoch: 10000
tol: 1e-6
gd: "SGD"   # available: "SGD" "MBGD"

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

wandb:
  project: "MLP"
  # dir: "./outputs"